CREATE TABLE [dbo].[Role]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
	[CreatedOn] SMALLDATETIME NOT NULL DEFAULT(GETDATE()),
    [DeletedOn] SMALLDATETIME NULL,
	[Name] VARCHAR(100) NOT NULL,
)
