version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: Queue
    hostname: hourly-queue
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq/
        - ./.containers/queue/log/:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
        RABBITMQ_DEFAULT_USER : guest
        RABBITMQ_DEFAULT_PASS: guest