CREATE TABLE [dbo].[UserClaim]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Uid] UNIQUEIDENTIFIER NOT NULL,
	[Type] VARCHAR(50) NOT NULL,
	[Value] VARCHAR(50) NOT NULL,
	[ConcurrencyStamp] VARCHAR(255) NULL,
	[UserId] INT NOT NULL,
	CONSTRAINT [FK_UserId] FOREIGN KEY ([UserId]) REFERENCES [User] ([Id]) ON DELETE CASCADE ON UPDATE NO ACTION
);

GO
CREATE INDEX [IX_UserClaims_UserId] ON [UserClaim] ([UserId] ASC);

