CREATE TABLE [dbo].[Permission]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
	[CreatedOn] SMALLDATETIME NOT NULL DEFAULT(GETDATE()),
    [DeletedOn] SMALLDATETIME NULL,
	[Name] VARCHAR(100) NOT NULL,
	[RoleId] INT NOT NULL,
	CONSTRAINT [FK_Permission_Role_ID] FOREIGN KEY ([RoleId]) REFERENCES [Role] ([Id]) ON DELETE CASCADE ON UPDATE NO ACTION,
)
