CREATE TABLE [dbo].[UserLogin]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
	[CreatedOn] SMALLDATETIME NOT NULL,
    [DeletedOn] SMALLDATETIME NULL,
	[Provider] VARCHAR(200) NOT NULL,
	[ProviderIdentityKey] VARCHAR(200) NOT NULL,
	[UserId] INT NOT NULL,
	[ConcurrencyStamp] VARCHAR(255) NULL,
	CONSTRAINT [FK_User] FOREIGN KEY ([UserId]) REFERENCES [User] ([Id]) ON DELETE CASCADE ON UPDATE NO ACTION
);

GO
CREATE INDEX [IX_UserLogin_UserId] ON [UserLogin] ([UserId] ASC);
